export const WEBSITE_BASE_URL = 'https://grocerapp.vercel.app'
export const PRODUCTS_BASEURL = 'https://grocerapp-products.vercel.app/products'
export const ORDERS_BASEURL = 'https://grocerapp-orders.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://grocerapp-shipping.vercel.app/shipping'
export const NOTIFICATIONS_BASEURL = 'https://grocerapp-notifications.vercel.app/notifications'
